# example netlify.toml
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/


[[edge_functions]]
function = "get-geo"
path = "/*"

[[redirects]]
  from = "/notes/*"
  to = "https://adamgray.dev/notes/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "https://adamgray.dev/images/:splat"
  status = 200

[[redirects]]
  from = "/notion/*"
  to = "https://gabygoldberg.notion.site/f7050e62461143d49345e7b46eb5576b?v=c02511c4230c44ce9a1a03c9757da524/:splat"
  status = 200